### ISSUE TITLE
Add dedicated Index class for unique, non-sparse String fields

### ISSUE THREAD

**Issue by justlep** [justlep/nedb#1]
The `Index` class internally uses `AVLTree` even for unique, non-sparse indexed fields like `_id`.
Index performance could (most likely) be improved by using a native `Map` instead of `AVLTree` for such fields.

**TODO**
* [x] add a `UniqueStringIndex` class extending or implementing the existing `Index` class
* [x] override all relevant methods to use a native `Map` internally
* [x] make  `UniqueStringIndex.getBetweenBounds()` throw (irrelevant usecase)
* [x] make `Datastore` use `UniqueStringIndex` for the `_id` field by default
* [ ] find a way to enable a developer to use UniqueStringIndex for other string indexes as well
* [ ] compare benchmarks before/after
